### ISSUE TITLE
Choppy value distribution

### ISSUE THREAD

**Issue by WilliamKappler** [pvigier/perlin-numpy#10]
I noticed that the noise generated by this library shows some sort of choppiness. I'm not entirely sure if this is due to how the image is being saved vs. generated, but it's present in the example image in your readme. Here's the second readme noise map's histogram:

![image](https://user-images.githubusercontent.com/13572055/146701871-0386f193-d93e-4b26-893b-e7d0ec75a146.png)

It doesn't seem to be caused by octaves. Here's a smoother one:

![image](https://user-images.githubusercontent.com/13572055/146701946-4964710b-fce9-4d0a-9ee5-4af2a8a1332f.png)

Perhaps there's rounding going on somewhere it shouldn't be?

Also, it isn't just GIMP. I tried a few different tools and they all show similar histogram anomalies.

**Comment by pvigier** [comment]
Hi,

I think it's due to how the image is saved. The noise was scaled on the example images, the noise is 256x256 but the part of the image that shows the noise is 369x368. So some values are repeated/interpolated.

If you use this piece of code to generate the images:
```python
import numpy as np
import PIL.Image
from perlin_numpy import (
    generate_perlin_noise_2d, generate_fractal_noise_2d
)

np.random.seed(0)
noise = generate_perlin_noise_2d((256, 256), (8, 8))
image = PIL.Image.fromarray(((noise + 1.0) / 2.0 * 255.0).astype(np.uint8), mode='L')
image.save('noise.png')

np.random.seed(0)
noise = generate_fractal_noise_2d((256, 256), (8, 8), 5)
image = PIL.Image.fromarray(((noise + 2.0) / 4.0 * 255.0).astype(np.uint8), mode='L')
image.save('fractal.png')
```
You should obtain these two images which don't show any anomaly in their histograms:
![noise](https://user-images.githubusercontent.com/934316/146752635-bf4c9d6e-dc75-4475-829f-591494abf26b.png)
![fractal](https://user-images.githubusercontent.com/934316/146752631-09cd8a45-9632-4926-9fa1-9acf5b4ec4c4.png)
